<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>MyWealthV2.IdentityHost</RootNamespace>
    <AssemblyName>MyWealthV2.IdentityHost</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
    <ProjectReference Include="..\ServiceDefaults\ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenIddict.AspNetCore" />
  </ItemGroup>

</Project>
